export const REACT_APP_BACK_URL = process.env.REACT_APP_BACK_URL || 'http://localhost:4000/api'
export const REACT_APP_GOOGLE_CLIENT_ID = process.env.REACT_APP_GOOGLE_CLIENT_ID
export const REACT_APP_GITHUB_CLIENT_ID = process.env.REACT_APP_GITHUB_CLIENT_ID
export const REACT_APP_LINKEDIN_CLIENT_ID = process.env.REACT_APP_LINKEDIN_CLIENT_ID
export const REACT_APP_API_CLOUDINARY = process.env.REACT_APP_API_CLOUDINARY